import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const B='http://localhost:18180';
const b=await chromium.launch();
const p=await b.newPage({viewport:{width:390,height:844}});
await p.goto(B);
await p.getByRole('button',{name:'Join free',exact:true}).click();
const handle='avfail_'+Date.now();
await p.getByRole('textbox',{name:'Username',exact:true}).fill(handle);
await p.getByRole('textbox',{name:'Password',exact:true}).fill('qa-only-password');
await p.getByRole('button',{name:'Sign up',exact:true}).click();
await p.getByRole('button',{name:'I saved it, continue'}).click();
await p.getByRole('button',{name:'profile',exact:true}).click();
await p.getByRole('button',{name:'Edit profile',exact:true}).click();
await p.locator('.editm input[type=file]').setInputFiles('seed/p1.jpg');
await p.getByRole('button',{name:'Save',exact:true}).click();
await p.getByRole('dialog').waitFor({state:'hidden'});
await p.waitForFunction(()=>document.querySelector('.prof .av')?.getAttribute('style')?.includes('url('));
// Avatar bytes now fail to load (expired upload, network loss): identity must fall back to the initial, not a broken image.
await p.route('**/uploads/**',r=>r.abort());
await p.reload();
await p.getByRole('button',{name:'home',exact:true}).waitFor();
await p.getByRole('button',{name:'profile',exact:true}).click();
await p.waitForFunction(()=>!document.querySelector('.prof .av')?.getAttribute('style')?.includes('url('));
assert.equal(await p.locator('.prof .av').first().innerText(),'A');
await p.screenshot({path:'/downloads/threadline-qa/avatar-failure-profile.png'});
await p.getByRole('button',{name:'home',exact:true}).click();
await p.locator('.story.add').waitFor();
assert.equal(await p.locator('.story.add .av').innerText(),'A');
await p.screenshot({path:'/downloads/threadline-qa/avatar-failure-feed.png'});
await p.unroute('**/uploads/**');
await p.reload();
await p.getByRole('button',{name:'profile',exact:true}).click();
await p.waitForFunction(()=>document.querySelector('.prof .av')?.getAttribute('style')?.includes('url('));
console.log('Failed avatar image falls back to initials on profile and stories; recovery restores photo: passed');
await b.close();
