import {firefox} from 'playwright';
import assert from 'node:assert/strict';
import AxeBuilder from '@axe-core/playwright';
const B='http://localhost:18180';
const b=await firefox.launch();
const c=await b.newContext({viewport:{width:390,height:844}});const p=await c.newPage();
await p.goto(B);
await p.getByRole('button',{name:'Join free',exact:true}).click();
await p.getByRole('textbox',{name:'Username',exact:true}).fill('ff_'+Date.now());
await p.getByRole('textbox',{name:'Password',exact:true}).fill('qa-only-password');
await p.getByRole('button',{name:'Sign up',exact:true}).click();
await p.getByRole('button',{name:'I saved it, continue'}).click();
await p.getByRole('button',{name:'create',exact:true}).click();
await p.locator('input[type=file]').setInputFiles('seed/p1.jpg');
await p.getByLabel('Caption',{exact:true}).fill('Firefox field note');
await p.getByRole('button',{name:'Share',exact:true}).click();
await p.getByRole('button',{name:'Edit profile',exact:true}).waitFor();
await p.getByRole('button',{name:'home',exact:true}).click();
const image=p.locator('.post .media img').first();
await image.waitFor();
await image.evaluate(e=>e.decode());
const ratio=await image.evaluate(e=>e.naturalWidth/e.naturalHeight);
const box=await image.boundingBox();
assert(Math.abs(box.width/box.height-ratio)<.02,'Whole photograph ratio in Firefox');
// Mouse double-click like path
await p.locator('.media').first().dblclick();
await p.getByRole('button',{name:'Unlike',exact:true}).waitFor();
assert.equal(await p.locator('.count').first().innerText(),'1 like');
await p.locator('.media').first().dblclick();
await p.waitForTimeout(350);
assert.equal(await p.locator('.count').first().innerText(),'1 like','Second double-click must not unlike');
await p.screenshot({path:'/downloads/threadline-qa/firefox-feed-light.png'});
// Theme toggle persists across reload
await p.getByRole('button',{name:'Toggle dark mode'}).click();
assert.equal(await p.locator('meta[name=theme-color]').getAttribute('content'),'#1b1b18');
await p.reload();
await p.getByRole('button',{name:'home',exact:true}).waitFor();
assert.equal(await p.locator('.ig').getAttribute('class'),'ig dark');
await p.locator('.post .media img').first().evaluate(e=>e.decode());
await p.waitForTimeout(300);
await p.screenshot({path:'/downloads/threadline-qa/firefox-feed-dark.png'});
// Story upload + viewer
await p.locator('.story.add input').setInputFiles('seed/p2.jpg');
await p.locator('.story:not(.add)').waitFor();
await p.locator('.story:not(.add)').click();
await p.getByRole('dialog').waitFor();
await p.locator('.sv-card img').evaluate(e=>e.decode());
await p.waitForTimeout(500);
await p.screenshot({path:'/downloads/threadline-qa/firefox-story-dark.png'});
await p.keyboard.press('Escape');
assert.equal(await p.getByRole('dialog').count(),0);
// Search finds own post by caption
await p.getByRole('button',{name:'explore',exact:true}).click();
await p.getByRole('textbox',{name:'Search people and posts'}).fill('Firefox field note');
await p.locator('.grid button').first().waitFor();
assert.equal(await p.locator('.grid button').count(),1);
await p.screenshot({path:'/downloads/threadline-qa/firefox-search-dark.png'});
assert.deepEqual((await new AxeBuilder({page:p}).analyze()).violations.map(v=>v.id),[]);
console.log('Firefox: signup, post, whole-aspect feed, double-click like/no-unlike, theme persistence, story viewer, caption search, axe clean: passed');
await b.close();
