import {spawn} from 'node:child_process';import {chromium,webkit} from 'playwright';import AxeBuilder from '@axe-core/playwright';import assert from 'node:assert/strict';import fs from 'node:fs';
const child=spawn(process.execPath,['test/preview.mjs'],{stdio:'ignore'});const B='http://localhost:18180';fs.mkdirSync('/downloads/threadline-qa',{recursive:true});let browsers=[];
try{
 for(let i=0;i<80;i++){try{if((await fetch(B+'/api/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 for(const engine of[chromium,webkit]){const b=await engine.launch();browsers.push(b);for(const viewport of[{width:390,height:844},{width:1440,height:1000},{width:320,height:568}]){const c=await b.newContext({viewport,serviceWorkers:'block'}),p=await c.newPage();const h='reels_'+Date.now();const r=await fetch(B+'/api/auth/signup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({handle:h,name:'Reels QA',password:'qa-only-password'})});const u=await r.json();await p.addInitScript(t=>localStorage.setItem('tl_token',t),u.token);await p.goto(B);const mobile=viewport.width<700;await p.getByRole('button',{name:mobile?'reels':'Reels',exact:true}).click();await p.getByText('Video discovery is not configured yet.',{exact:true}).waitFor();assert.equal(await p.locator('iframe').count(),0);
 for(const dark of[false,true]){if(dark)await p.getByRole('button',{name:mobile?'Toggle dark mode':'Dark mode',exact:true}).click();await p.waitForTimeout(450);let axe=await new AxeBuilder({page:p}).analyze();assert.deepEqual(axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.failureSummary)})),[]);await p.screenshot({path:`/downloads/threadline-qa/reels-${engine.name()}-${viewport.width}-${dark?'dark':'light'}-blocked.png`});}
 let requests=0;await p.route('**/api/reels*',route=>{requests++;return route.fulfill({json:{items:[{id:'abcDEF123_-',title:'A real-world clip with a long accessible title',channel:'Studio',source:'YouTube',watchUrl:'https://www.youtube.com/watch?v=abcDEF123_-',embedUrl:'https://www.youtube-nocookie.com/embed/abcDEF123_-'}],next:null,notice:'Discovery has daily limits.'}});});await p.getByRole('button',{name:'Try again',exact:true}).focus();await p.keyboard.press('Enter');await p.getByRole('heading',{name:'A real-world clip with a long accessible title'}).waitFor();assert.equal(await p.locator('iframe').count(),0);let embeds=0;await p.route('https://www.youtube-nocookie.com/**',route=>{embeds++;return route.fulfill({contentType:'text/html',body:'<!DOCTYPE html><html><head><title>Local player test</title></head><body style="background:#171714;color:white"><main>Local test player, not live YouTube footage</main></body></html>'});});await p.getByRole('button',{name:'Allow YouTube playback'}).click();await p.locator('iframe').waitFor();await p.screenshot({path:`/downloads/threadline-qa/reels-${engine.name()}-${viewport.width}-playing.png`});assert.equal(await p.locator('iframe').count(),1);assert.equal(embeds,1);await p.getByRole('button',{name:'Pause playback'}).click();assert.equal(await p.locator('iframe').count(),0);await p.getByRole('button',{name:'Resume playback'}).click();await p.locator('iframe').waitFor();await p.getByRole('button',{name:'Stop YouTube playback'}).click();assert.equal(await p.locator('iframe').count(),0);assert.equal(requests,1);const profile=p.getByRole('button',{name:mobile?'profile':'Profile',exact:true});const bounds=await profile.boundingBox();assert(bounds&&bounds.x+bounds.width<=viewport.width+1);assert.equal(await p.locator('.reels-scroll').evaluate(el=>el.scrollWidth<=el.clientWidth),true);const a=await new AxeBuilder({page:p}).analyze();assert.deepEqual(a.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.failureSummary)})),[]);await p.screenshot({path:`/downloads/threadline-qa/reels-${engine.name()}-${viewport.width}-populated.png`});await c.close();}}
 console.log('Reels UI: Chromium/WebKit 320/390/1440; real unconfigured API, consent-gated single embed, pause/resume/revoke, end state, unrestricted axe: passed. Local playback response is mocked, no live-video claim.');
}finally{await Promise.all(browsers.map(b=>b.close()));child.kill();}
