import React, { useCallback, useEffect, useRef, useState, useId } from 'react';
import { api, hasToken, setToken, readStored, writeStored, setOnAuthLost, img, Post, User, Comment, Notif, Convo, Msg, Mini, StoryGroup } from './api';
import { Landing } from './Landing';
import './style.css';
function BrandMark(){return <svg className="brand-mark" aria-hidden="true" viewBox="0 0 24 28" fill="none" stroke="currentColor" strokeWidth="1.6"><path d="M8 2H3v24h5M16 2h5v24h-5M9 8l6 4-6 4 6 4"/></svg>}

type Tab = 'home' | 'explore' | 'create' | 'messages' | 'activity' | 'saved' | 'profile';
const Ic = ({ d, fill, size = 24 }: { d: string; fill?: boolean; size?: number }) =>
  <svg width={size} height={size} viewBox="0 0 24 24" fill={fill ? 'currentColor' : 'none'} stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={d} /></svg>;
const I = {
  home: 'M3 11l9-8 9 8v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z', search: 'M11 4a7 7 0 1 0 0 14 7 7 0 0 0 0-14zM21 21l-5-5', plus: 'M12 5v14M5 12h14',
  heart: 'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1-1.1a5.5 5.5 0 0 0-7.8 7.8l1 1.1L12 21l7.8-7.5 1-1.1a5.5 5.5 0 0 0 0-7.8z',
  comment: 'M21 11.5a8.4 8.4 0 0 1-12.4 7.4L3 20.5l1.6-5.5A8.4 8.4 0 1 1 21 11.5z', bookmark: 'M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z',
  user: 'M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8z', close: 'M18 6L6 18M6 6l12 12', moon: 'M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z',
  send: 'M22 2L11 13M22 2l-7 20-4-9-9-4z',
  bell: 'M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9M13.7 21a2 2 0 0 1-3.4 0',
  trash: 'M3 6h18M8 6V4h8v2M19 6l-1 14H6L5 6', logout: 'M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4M16 17l5-5-5-5M21 12H9',
};
const hue = (s: string) => [...s].reduce((a, c) => (a * 31 + c.charCodeAt(0)) % 360, 7);
const ring = (_h: number) => 'var(--blue)';
const ago = (t: number) => { const s = Math.max(1, (Date.now() - t) / 1000); return s < 60 ? 'now' : s < 3600 ? Math.floor(s / 60) + 'm' : s < 86400 ? Math.floor(s / 3600) + 'h' : Math.floor(s / 86400) + 'd'; };

function Avatar({ handle, name, size = 40, story, src }: { handle: string; name?: string; size?: number; story?: boolean; src?: string | null }) {
  const h=hue(handle);const[failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);const photo=!!src&&!failed;
  return <span className="av-wrap" style={{ width: size + (story ? 8 : 0), height: size + (story ? 8 : 0), background: story ? ring(h) : 'transparent' }}>
    <span className="av" style={{ width: size, height: size, fontSize: size * 0.4, background:photo?`center/cover url(${img(src!)})`: 'var(--soft)' }}>{photo?<img src={img(src!)} alt="" onError={()=>setFailed(true)}/>:((name||handle)[0]||'?').toUpperCase()}</span></span>;
}

async function toDataUrl(file:File,maxSide=1440):Promise<string>{
  if(file.size>20*1024*1024)throw new Error('Choose an image smaller than 20 MB');
  let source:ImageBitmap|HTMLImageElement;let cleanup=()=>{};
  let bitmap:ImageBitmap|undefined;if(typeof createImageBitmap==='function'){try{bitmap=await createImageBitmap(file);}catch{/* Some browsers expose this API but reject supported image formats. */}}
  if(bitmap){source=bitmap;cleanup=()=>bitmap!.close();}
  else{const url=URL.createObjectURL(file);const image=new Image();try{await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error('That file could not be read as an image.'));image.src=url;});source=image;cleanup=()=>URL.revokeObjectURL(url);}catch(e){URL.revokeObjectURL(url);throw e;}}
  try{const width=source instanceof HTMLImageElement?source.naturalWidth:source.width;const height=source instanceof HTMLImageElement?source.naturalHeight:source.height;if(!width||!height)throw new Error('That image has no readable dimensions');const k=Math.min(1,maxSide/Math.max(width,height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(width*k));c.height=Math.max(1,Math.round(height*k));const x=c.getContext('2d');if(!x)throw new Error('Your browser could not prepare that photo');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(source,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.85);}finally{cleanup();}
}

function Auth({ onAuth, initial = 'login', onBack }: { onAuth: (u: User) => void; initial?: 'login' | 'signup'; onBack?: () => void }) {
  const [copied,setCopied]=useState(false);const[copying,setCopying]=useState(false);const copyLock=useRef(false);const copyOperation=useRef(0);useEffect(()=>()=>{copyOperation.current++;},[]);const [showPassword,setShowPassword]=useState(false);const [sessionSaved,setSessionSaved]=useState(true);const [mode, setMode] = useState<'login' | 'signup' | 'reset'>(initial); const [code, setCode] = useState(''); const [shown, setShown] = useState<{ code: string; user: User } | null>(null); const [handle, setHandle] = useState(''); const [name, setName] = useState(''); const [pw, setPw] = useState(''); const [err, setErr] = useState(''); const [busy,setBusy]=useState(false);const authLock=useRef(false);const recoveryHeading=useRef<HTMLHeadingElement>(null);useEffect(()=>{if(shown)recoveryHeading.current?.focus({preventScroll:true});},[shown]);
  const submit = async (e: React.FormEvent) => { e.preventDefault();if(authLock.current)return;authLock.current=true;setErr('');setBusy(true);
    try { const r: any = mode === 'login' ? await api.login(handle, pw) : mode === 'reset' ? await api.reset(handle, code, pw) : await api.signup(handle, name || handle, pw); setSessionSaved(setToken(r.token)); if (r.recoveryCode) setShown({ code: r.recoveryCode, user: r.user }); else onAuth(r.user); }
    catch (x: any) { setErr(x.message); } finally{authLock.current=false;setBusy(false);} };
  if (shown) return <div className="authwrap" role="main"><div className="authcard"><h1 ref={recoveryHeading} tabIndex={-1} className="logo" style={{ fontSize: 28 }}>Save your recovery code</h1><p className="tag">If you forget your password, this code is the only way back in. We never email you, so write it down.</p>
    {!sessionSaved&&<p className="tag">Your browser is not allowing saved sessions. You can use Threadline now, but will need to sign in again after closing or reloading it.</p>}<div className="rcode" data-testid="recovery-code">{shown.code}</div>
    <button type="button" className="ghost" disabled={copying} onClick={async () => {if(copyLock.current)return;copyLock.current=true;const id=++copyOperation.current;setCopying(true);try{await navigator.clipboard.writeText(shown.code);if(id===copyOperation.current){setCopied(true);setErr('');}}catch{if(id===copyOperation.current){setCopied(false);setErr('Copy is unavailable. Select and save the code manually.');}}finally{if(id===copyOperation.current){copyLock.current=false;setCopying(false);}}}}>{copying?'Copying…':copied?'Copied':'Copy code'}</button>{copied&&<span className="sr-only" role="status">Recovery code copied</span>}
    <p className="mut tiny">Keep this private, just like your password.</p>{err && <p className="err" role="alert">{err}</p>}<button className="primary" onClick={() => onAuth(shown.user)}>I saved it, continue</button></div></div>;
  return <div className="authwrap" role="main"><form className="authcard" onSubmit={submit}>
    {onBack && <button type="button" className="back" disabled={busy} onClick={onBack}>← Back</button>}<h1 className="logo"><BrandMark />Threadline</h1><p className="tag">Your people. Your perspective.</p>
    <input disabled={busy} aria-label="Username" placeholder="Username" value={handle} onChange={e => setHandle(e.target.value)} autoCapitalize="none" autoComplete="username" required />
    {mode === 'signup' && <input disabled={busy} aria-label="Full name" placeholder="Full name" value={name} onChange={e => setName(e.target.value)} autoComplete="name" />}
    {mode === 'reset' && <input disabled={busy} aria-label="Recovery code" placeholder="Recovery code (XXXX-XXXX-XXXX)" value={code} onChange={e => setCode(e.target.value)} autoCapitalize="characters" autoComplete="off" required />}
    <input disabled={busy} aria-label={mode === 'reset' ? 'New password' : 'Password'} placeholder={mode === 'reset' ? 'New password' : 'Password'} type={showPassword?'text':'password'} value={pw} onChange={e => setPw(e.target.value)} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} required maxLength={1024} minLength={mode==='login'?1:8}/><button type="button" className="password-toggle" aria-pressed={showPassword} disabled={busy} onClick={()=>setShowPassword(v=>!v)}>{showPassword?'Hide password':'Show password'}</button>
    {err && <p className="err" role="alert">{err}</p>}
    <button className="primary" disabled={busy}>{busy ? 'One moment…' : mode === 'login' ? 'Log in' : mode === 'reset' ? 'Reset password' : 'Sign up'}</button>
    {mode === 'login' && <p className="swap"><button type="button" disabled={busy} onClick={() => { setMode('reset');setPw('');setShowPassword(false);setCode('');setErr(''); }}>Forgot password?</button></p>}
    <p className="swap">{mode === 'login' ? 'New here?' : mode === 'reset' ? 'Remembered it?' : 'Have an account?'} <button type="button" disabled={busy} onClick={() => { setMode(mode === 'signup' ? 'login' : mode === 'reset' ? 'login' : 'signup');setPw('');setShowPassword(false);setCode('');setErr(''); }}>{mode === 'login' ? 'Sign up' : 'Log in'}</button></p>
  </form></div>;
}

function PostCard({ post, me, onChange, onOpen, onUser, onDelete, priority = false }: { priority?: boolean; post: Post; me: User; onChange: (p: Post) => void; onOpen?: () => void; onUser: (h: string) => void; onDelete:(id:number)=>Promise<boolean> }) {
  const [text, setText] = useState(''); const [burst, setBurst] = useState(false); const [err, setErr] = useState(''); const [pending, setPending] = useState(false); const [deleting,setDeleting]=useState(false);const [mediaFailed,setMediaFailed]=useState(false);const [mediaLoaded,setMediaLoaded]=useState(false);const [mediaRetry,setMediaRetry]=useState(0);const tapped=useRef({time:0,x:0,y:0});const touchStart=useRef({x:0,y:0}); const pendingLock=useRef(false);const burstTimer=useRef<ReturnType<typeof setTimeout>>();
  useEffect(() => () => clearTimeout(burstTimer.current), []);
  const act = async (f: () => Promise<Post>) => {if(pendingLock.current)return false;pendingLock.current=true;setPending(true); setErr(''); try { onChange(await f()); return true; } catch (e: any) { setErr(e.message); return false; } finally{pendingLock.current=false;setPending(false);} };
  const like = () => act(() => api.like(post.id, !post.liked));
  const dbl = () => { setBurst(true); clearTimeout(burstTimer.current); burstTimer.current = setTimeout(() => setBurst(false), 700); if (!post.liked) like(); };
  const send = async (e: React.FormEvent) => { e.preventDefault(); const t = text.trim(); if (!t) return; if (await act(() => api.comment(post.id, t))) setText(''); };
  return <article className="post">
    <header><button aria-label={"Open profile of " + post.user.handle} onClick={() => onUser(post.user.handle)}><Avatar handle={post.user.handle} name={post.user.name} size={32} src={post.user.avatar} /></button><div><button className="post-author" aria-label={"View profile of " + post.user.handle} onClick={() => onUser(post.user.handle)}>{post.user.handle}</button></div><span className="ago">{ago(post.created)}</span>
      {post.user.id === me.id && <button className="out" aria-label="Delete post" onClick={() => setDeleting(v=>!v)} aria-expanded={deleting}><Ic d={I.trash} size={18} /></button>}</header>
    {deleting&&<div className="delete-confirm" role="alert"><p>Delete this photo? This cannot be undone.</p><div><button className="ghost" disabled={pending} onClick={()=>setDeleting(false)}>Keep photo</button><button className="danger" disabled={pending} onClick={async()=>{if(pendingLock.current)return;pendingLock.current=true;setPending(true);setErr('');try{if(await onDelete(post.id))setDeleting(false);else setErr('Could not delete this photo. Please try again.');}finally{pendingLock.current=false;setPending(false);}}}>{pending?'Deleting…':'Delete photo'}</button></div></div>}
    <div className={"media"+(post.width&&post.height?" measured":"")+(!mediaLoaded?" awaiting":"")+(mediaFailed?" failed":"")} style={post.width&&post.height?{aspectRatio:post.width+" / "+post.height}:undefined} onDoubleClick={e => { if (mediaFailed) return; if (e.nativeEvent instanceof MouseEvent && !(e.nativeEvent as any).sourceCapabilities?.firesTouchEvents) dbl(); }} onPointerDown={e=>{if(e.pointerType==='touch')touchStart.current={x:e.clientX,y:e.clientY};}} onPointerCancel={()=>{tapped.current={time:0,x:0,y:0};}} onPointerUp={e=>{if(e.pointerType!=='touch'||mediaFailed)return;if(Math.abs(e.clientX-touchStart.current.x)>15||Math.abs(e.clientY-touchStart.current.y)>15){tapped.current={time:0,x:0,y:0};return;} const now=performance.now(); const last=tapped.current; if (now-last.time<300 && Math.abs(e.clientX-last.x)<30 && Math.abs(e.clientY-last.y)<30) { dbl(); tapped.current={time:0,x:0,y:0}; } else tapped.current={time:now,x:e.clientX,y:e.clientY}; }}><img key={mediaRetry} src={img(post.image)+(mediaRetry?'?retry='+mediaRetry:'')} alt={post.caption||'Photo'} loading={priority?"eager":"lazy"} fetchPriority={priority?"high":"auto"} decoding="async" width={post.width||undefined} height={post.height||undefined} onError={()=>{setMediaFailed(true);setMediaLoaded(false);}} onLoad={()=>{setMediaFailed(false);setMediaLoaded(true);}}/>{mediaFailed&&<div className="media-error" role="status"><p>This photo could not load.</p><button className="ghost" onClick={e=>{e.stopPropagation();setMediaFailed(false);setMediaLoaded(false);setMediaRetry(n=>n+1);}}>Reload photo</button></div>}{burst && <span className="burst" aria-hidden><Ic d={I.heart} fill size={90} /></span>}</div>
    <div className="actions">
      <button key={'l' + post.liked} className={post.liked ? 'liked pulse' : ''} disabled={pending} onClick={like} aria-label={post.liked ? "Unlike" : "Like"} aria-pressed={post.liked}><Ic d={I.heart} fill={post.liked} /></button>
      <button onClick={onOpen} aria-label="View comments"><Ic d={I.comment} /></button>
      <button key={'s' + post.saved} className={'push' + (post.saved ? ' pulse' : '')} onClick={() => act(() => api.save(post.id, !post.saved))} disabled={pending} aria-label={post.saved ? "Unsave" : "Save"} aria-pressed={post.saved}><Ic d={I.bookmark} fill={post.saved} /></button>
    </div>
    <div className="meta"><b key={post.likes} className="count">{post.likes.toLocaleString()} {post.likes === 1 ? 'like' : 'likes'}</b>
      {post.caption && <p className="post-caption"><b>{post.user.handle}</b> {post.caption}</p>}
      {post.comments.map(c => <p className="post-comment" key={c.id}><b>{c.handle}</b> {c.text}</p>)}
      {post.commentCount > post.comments.length && <button className="link" onClick={onOpen}>View all {post.commentCount} comments</button>}
      {err && <p className="err" role="alert">{err}</p>}</div>
    <form className="comment" onSubmit={send}><input value={text} onChange={e => setText(e.target.value)} aria-label="Add a comment" placeholder="Add a comment…" maxLength={500} /><button disabled={!text.trim() || pending}>Post</button></form>
  </article>;
}

function useDialog(onClose: () => void) {
  const ref=useRef<HTMLDivElement>(null);
  const close=useRef(onClose);close.current=onClose;
  useEffect(()=>{
    const old=document.activeElement as HTMLElement;
    const overflow=document.body.style.overflow;
    const scroll={left:window.scrollX,top:window.scrollY};
    document.body.style.overflow='hidden';
    const el=ref.current;
    const isolated:HTMLElement[]=[];
    let node=el?.parentElement;
    while(node&&node!==document.body){
      for(const sibling of Array.from(node.parentElement?.children||[])){
        if(sibling!==node&&sibling instanceof HTMLElement&&!sibling.inert){sibling.inert=true;isolated.push(sibling);}
      }
      node=node.parentElement;
    }
    el?.focus({preventScroll:true});
    const key=(e:KeyboardEvent)=>{
      if(e.key==='Escape'){e.preventDefault();close.current();return;}
      if(e.key!=='Tab'||!el)return;
      const controls=Array.from(el.querySelectorAll<HTMLElement>('button,input,textarea,select,a[href],[tabindex]'))
        .filter(x=>!x.matches(':disabled,[type=hidden]')&&x.tabIndex>=0&&x.getClientRects().length>0&&getComputedStyle(x).visibility!=='hidden');
      if(!controls.length){e.preventDefault();el.focus({preventScroll:true});return;}
      const current=document.activeElement;
      if(!controls.includes(current as HTMLElement)){
        e.preventDefault();(e.shiftKey?controls[controls.length-1]:controls[0]).focus();
      }else if(e.shiftKey&&current===controls[0]){
        e.preventDefault();controls[controls.length-1].focus();
      }else if(!e.shiftKey&&current===controls[controls.length-1]){
        e.preventDefault();controls[0].focus();
      }
    };
    document.addEventListener('keydown',key);
    return()=>{
      document.body.style.overflow=overflow;
      isolated.forEach(x=>{x.inert=false;});
      document.removeEventListener('keydown',key);
      if(old?.isConnected)old.focus({preventScroll:true});
      window.scrollTo({...scroll,behavior:'instant'});
    };
  },[]);
  return ref;
}
function Modal({ post, me, onChange, onClose, onUser, onDelete }: { post: Post; me: User; onChange: (p: Post) => void; onClose: () => void; onUser: (h: string) => void; onDelete:(id:number)=>Promise<boolean> }) {
  const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);const dialog=useDialog(onClose); const [all,setAll]=useState<Comment[]|null>(null);useEffect(()=>{setAll(null);},[post.id]);const [commentsLoading,setCommentsLoading]=useState(true);const [commentsErr,setCommentsErr]=useState('');const [commentsRetry,setCommentsRetry]=useState(0);
  useEffect(()=>{let active=true;setCommentsLoading(true);setCommentsErr('');api.comments(post.id).then(r=>{if(active)setAll(r.comments);}).catch(e=>{if(active)setCommentsErr(e.message);}).finally(()=>{if(active)setCommentsLoading(false);});return()=>{active=false;};},[post.id,post.commentCount,commentsRetry]);
  return <div className="scrim" onClick={onClose}><div ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-label="Post and comments" className="modal" onClick={e => e.stopPropagation()}>
    <div className="modal-tools"><span>Photograph</span><button className="x" onClick={onClose} aria-label="Close"><Ic d={I.close} /></button></div>
    <PostCard priority post={{ ...post, comments: all===null?post.comments:Array.from(new Map([...all,...post.comments].map(c=>[c.id,c])).values()).sort((a,b)=>a.id-b.id) }} me={me} onChange={onChange} onUser={h => { onClose(); onUser(h); }} onDelete={async id=>{const ok=await onDelete(id);if(ok&&mounted.current)onClose();return ok;}} />{commentsLoading&&<p className="comments-status" role="status">Loading comments…</p>}{commentsErr&&<div className="comments-status err" role="alert"><p>{commentsErr}</p><button className="ghost" onClick={()=>setCommentsRetry(n=>n+1)}>Try again</button></div>}</div></div>;
}

function GridImage({src}:{src:string}){const[failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);return failed?<span className="grid-failed"><Ic d={I.comment} size={22}/><small>Photo unavailable</small></span>:<img src={img(src)} alt="" loading="lazy" onError={()=>setFailed(true)}/>;}
function NotificationImage({src}:{src:string}){const[failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[src]);return failed?<span className="notification-image-failed" role="img" aria-label="Photo preview unavailable" title="Photo preview unavailable"><Ic d={I.comment} size={18}/></span>:<img src={img(src)} alt="" onError={()=>setFailed(true)}/>;}
const Grid = ({ posts, onOpen }: { posts: Post[]; onOpen: (p: Post) => void }) => !posts.length ? <p className="empty">Nothing here yet.</p> :
  <div className={"grid"+(posts.length===1?" single":posts.length===2?" pair":"")}>{posts.map(p => <button aria-label={"Open photo by " + p.user.handle + (p.caption ? ": " + p.caption : "")} key={p.id} onClick={() => onOpen(p)}><GridImage src={p.image}/>
    <span className="hover"><Ic d={I.heart} fill size={18} /> {p.likes} <Ic d={I.comment} fill size={18} /> {p.commentCount}</span></button>)}</div>;

type PhotoDraft={src?:string;fileName:string;caption:string};
function Create({ done, draft, session, busy, setBusy, revision, changed, err, setErr }: { err:string;setErr:React.Dispatch<React.SetStateAction<string>>;done: () => void; draft: React.MutableRefObject<PhotoDraft>;session:React.MutableRefObject<number>;busy:boolean;setBusy:React.Dispatch<React.SetStateAction<boolean>>;revision:number;changed:()=>void }) {
  const [src, setSrc] = useState<string>(draft.current.src);const [fileName,setFileName]=useState(draft.current.fileName);const [reading,setReading]=useState(false);const [dragging,setDragging]=useState(false); const [cap, setCap] = useState(draft.current.caption); const ref = useRef<HTMLInputElement>(null);const pickId=useRef(0);const shareLock=useRef(false);const mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;pickId.current++;};},[]);
  useEffect(()=>{setSrc(draft.current.src);setFileName(draft.current.fileName);setCap(draft.current.caption);},[revision]);
  const pick=async(f?:File)=>{if(!f||busy)return;const id=++pickId.current;setReading(true);setErr('');try{const data=await toDataUrl(f);if(id===pickId.current){setSrc(data);setFileName(f.name);draft.current={...draft.current,src:data,fileName:f.name};}}catch(x:any){if(id===pickId.current)setErr(x.message||'That file could not be read as an image.');}finally{if(id===pickId.current)setReading(false);}};
  return <div className="create"><div className="section-heading"><h2>New photograph</h2><p>Choose a photo, then add a caption.</p></div>
    <button type="button" aria-label="Choose a photo" disabled={busy} className={'drop' + (src ? ' has' : '')+(dragging?' dragging':'')} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);pick(e.dataTransfer.files[0]);}} onClick={() => ref.current?.click()}>{src ? <img src={src} alt="Preview" /> : <><Ic d={I.plus} size={36} /><p>Choose a photo</p><small>JPG, PNG or WebP · Up to 20 MB</small></>}{reading&&<span className="photo-reading" role="status"><span className="spinner" aria-hidden="true"/>Preparing photo…</span>}</button>
    <input ref={ref} type="file" accept="image/*" hidden disabled={busy} onChange={e=>{pick(e.target.files?.[0]);e.target.value='';}} />
    {fileName&&<div className="file-note"><span>{fileName}</span><button type="button" className="link" disabled={busy} onClick={()=>{pickId.current++;setReading(false);setSrc(undefined);setFileName('');draft.current={...draft.current,src:undefined,fileName:''};}}>Remove</button></div>}<label className="caption-field"><span>Caption <small>Optional</small></span><textarea disabled={busy} aria-label="Caption" placeholder="A few words about this photograph…" value={cap} onChange={e => {setCap(e.target.value);draft.current={...draft.current,caption:e.target.value};}} rows={3} maxLength={2200} /></label>
    {err && <p className="err" role="alert">{err}</p>}
    <button className="primary" disabled={!src || busy || reading} onClick={async () => {if(shareLock.current||busy||!src||reading)return;shareLock.current=true;setBusy(true);setErr('');const generation=session.current;try { const submitted=draft.current;await api.createPost(src, cap);if(session.current!==generation)return;if(draft.current===submitted){draft.current={fileName:'',caption:''};setSrc(undefined);setFileName('');setCap('');changed();}setBusy(false);shareLock.current=false;if(mounted.current)done(); } catch (e: any) { if(session.current!==generation)return;setErr(e.message);setBusy(false);shareLock.current=false; } }}>{busy ? 'Sharing…' : 'Share'}</button></div>;
}

type MessageDrafts=Record<string,string>;
function Messages({ me, to, setTo, onUser, onRead, onExplore, drafts, setDrafts, pending, setPending, session, sendErrors, setSendErrors }: { sendErrors:Record<string,string>;setSendErrors:React.Dispatch<React.SetStateAction<Record<string,string>>>;drafts:MessageDrafts;setDrafts:React.Dispatch<React.SetStateAction<MessageDrafts>>;pending:Set<string>;setPending:React.Dispatch<React.SetStateAction<Set<string>>>;session:React.MutableRefObject<number>;onExplore: () => void; me: User; to: string | null; setTo: (h: string | null) => void; onUser: (h: string) => void; onRead: () => void }) {
  const [convos, setConvos] = useState<Convo[]>([]); const [thread, setThread] = useState<{ user: Mini; messages: Msg[] } | null>(null); const text=to?drafts[to]||'':'';const sending=!!to&&pending.has(to);const [err, setErr] = useState('');const sendLock=useRef(false);const end = useRef<HTMLDivElement>(null);const initialThread=useRef(true);const previousThreadCount=useRef(0);const [listLoading,setListLoading]=useState(true);const[listRetry,setListRetry]=useState(0);const[threadRetry,setThreadRetry]=useState(0);const activeTo=useRef(to);activeTo.current=to;const onReadRef=useRef(onRead);onReadRef.current=onRead;
  useEffect(() => { if (to) return;let active=true;let pulling=false;setErr('');setListLoading(true);const load=()=>{if(document.hidden||pulling)return;pulling=true;api.conversations().then(r=>{if(active){setConvos(r.conversations);setErr('');}}).catch(e=>{if(active)setErr(e.message);}).finally(()=>{pulling=false;if(active)setListLoading(false);});};load();const t=setInterval(load,15000);document.addEventListener('visibilitychange',load);return()=>{active=false;clearInterval(t);document.removeEventListener('visibilitychange',load);}; },[to,listRetry]);
  useEffect(()=>{initialThread.current=true;previousThreadCount.current=0;setThread(null);},[to]);
  useEffect(() => { setErr('');if (!to) return; let on=true;let pulling=false;const pull=()=>{if(pulling)return;pulling=true;return api.thread(to).then(r=> { if (on) { setThread(previous=>{const ids=new Set(r.messages.map(m=>m.id));return{...r,messages:[...r.messages,...(previous?.messages.filter(m=>m.mine&&!ids.has(m.id)&&m.id>(r.messages[r.messages.length-1]?.id||0))||[])]};});setErr(''); onReadRef.current(); } }).catch(e=>on&&setErr(e.message)).finally(()=>{pulling=false;});};pull();const visible=()=>{if(!document.hidden)pull();};const t=setInterval(visible,8000);document.addEventListener('visibilitychange',visible);return()=>{on=false;clearInterval(t);document.removeEventListener('visibilitychange',visible);}; }, [to,threadRetry]);
  useEffect(() => {if(!thread)return;const p=end.current?.parentElement;const first=initialThread.current;const count=thread.messages.length;const added=count>previousThreadCount.current;const mine=added&&thread.messages[count-1]?.mine;if(p&&(first||p.scrollHeight-p.scrollTop-p.clientHeight<180||mine))p.scrollTo({top:p.scrollHeight,behavior:first||matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});initialThread.current=false;previousThreadCount.current=count;},[thread?.messages.length]);
  const send = async (e: React.FormEvent) => {
    e.preventDefault();const original=text;const v=text.trim();
    if(!v||!to||sendLock.current||pending.has(to))return;
    sendLock.current=true;const recipient=to;const generation=session.current;
    setPending(p=>new Set(p).add(recipient));setSendErrors(es=>{const next={...es};delete next[recipient];return next;});setErr('');
    try{
      const m=await api.send(recipient,v);
      if(session.current!==generation)return;
      setDrafts(d=>{if(d[recipient]!==original)return d;const next={...d};delete next[recipient];return next;});
      if(activeTo.current===recipient)setThread(t=>t&&{...t,messages:t.messages.some(x=>x.id===m.id)?t.messages:[...t.messages,m]});
    }catch(x:any){if(session.current===generation)setSendErrors(es=>({...es,[recipient]:x.message}));}
    finally{sendLock.current=false;if(session.current===generation)setPending(p=>{const next=new Set(p);next.delete(recipient);return next;});}
  };
  const visibleError=err||(to?sendErrors[to]:'');
  if (to) return <div className="wide dm"><div className="dm-h"><button className="ghost" onClick={() => setTo(null)}>← Back</button>{thread && <button className="dm-u" onClick={() => onUser(thread.user.handle)}><Avatar handle={thread.user.handle} name={thread.user.name} size={36} src={thread.user.avatar} /><b>{thread.user.handle}</b></button>}</div>
    <div className="dm-body" tabIndex={0} role="region" aria-label="Conversation history">{!thread&&!err&&<div className="empty"><span className="spinner" aria-label="Loading conversation"/></div>}{thread && thread.messages.length === 0 && <p className="empty">Say hi to {thread.user.name}.</p>}
      {thread?.messages.map(m => <div key={m.id} className={'bub ' + (m.mine ? 'me' : 'them')}><span className="message-text">{m.text}</span><small>{ago(m.created)}</small></div>)}<div ref={end} /></div>
    {visibleError&&<div className="err" role="alert"><p>{visibleError}</p>{!thread&&<button className="ghost" onClick={()=>setThreadRetry(n=>n+1)}>Try again</button>}</div>}
    <form className="dm-in" onSubmit={send}><textarea rows={2} value={text} disabled={sending||!thread} onChange={e => {const value=e.target.value;if(to)setDrafts(d=>({...d,[to]:value}));}} onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)&&!e.nativeEvent.isComposing){e.preventDefault();e.currentTarget.form?.requestSubmit();}}} aria-label="Message" placeholder="Message…" maxLength={1000} /><button className="primary" disabled={!text.trim()||sending||!thread}>{sending?'Sending…':'Send'}</button></form></div>;
  return <div className="wide"><div className="section-heading"><h2>Messages</h2><p>Your conversations, in one place.</p></div>
    {listLoading&&<p className="empty" role="status">Loading conversations…</p>}{err&&<div className="err" role="alert"><p>{err}</p><button className="ghost" onClick={()=>setListRetry(n=>n+1)}>Try again</button></div>}{!listLoading&&!err&&convos.length === 0 && <div className="quiet-start"><h3>No conversations yet.</h3><p>Find someone on Explore. Open their profile to send a message.</p><button className="ghost" onClick={onExplore}>Find people</button></div>}
    {convos.map(c => <button key={c.user.id} className={'convo' + (c.unread ? ' new' : '')} onClick={() => setTo(c.user.handle)}><Avatar handle={c.user.handle} name={c.user.name} size={48} src={c.user.avatar} /><div><b>{c.user.handle}</b><span>{c.mine ? 'You: ' : ''}{c.text}</span></div>{c.unread > 0 && <i className="badge static">{c.unread}</i>}<small>{ago(c.created)}</small></button>)}</div>;
}
function StoryViewer({groups,start,onClose,me,onDeleted}:{groups:StoryGroup[];start:number;onClose:()=>void;me:User;onDeleted:()=>void}) {
  const[confirmDelete,setConfirmDelete]=useState(false);const[deleting,setDeleting]=useState(false);const[deleteErr,setDeleteErr]=useState('');const dismiss=()=>{if(!deleting)onClose();};const dialog=useDialog(dismiss); const [gi,setGi]=useState(start);const [ii,setIi]=useState(0);const [paused,setPaused]=useState(false);const [ready,setReady]=useState(false);const [elapsed,setElapsed]=useState(0);const [failed,setFailed]=useState(false);const[restart,setRestart]=useState(0);const g=groups[gi];const it=g.items[ii];const duration=5000;
  const press=useRef({time:0,x:0,y:0,wasPaused:false});const elapsedRef=useRef(0);const advancing=useRef(false);
  const next=useCallback(()=>{if(advancing.current)return;advancing.current=true;if(ii<g.items.length-1)setIi(ii+1);else if(gi<groups.length-1){setGi(gi+1);setIi(0);}else onClose();},[ii,gi,g,groups.length,onClose]);
  const prev=()=>{if(ii>0)setIi(ii-1);else if(gi>0){setGi(gi-1);setIi(groups[gi-1].items.length-1);}else{setElapsed(0);elapsedRef.current=0;setRestart(n=>n+1);}};
  useEffect(()=>{setReady(false);setFailed(false);setPaused(false);setElapsed(0);elapsedRef.current=0;advancing.current=false;},[it.id]);
  useEffect(()=>{if(!ready||paused||failed||confirmDelete||deleting)return;const started=performance.now();const previous=elapsedRef.current;let raf:number;const tick=()=>{const total=Math.min(duration,previous+performance.now()-started);elapsedRef.current=total;setElapsed(total);if(total>=duration)next();else raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[ready,paused,failed,next,confirmDelete,deleting,restart]);
  useEffect(()=>{const visibility=()=>{if(document.hidden)setPaused(true);};document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility);},[]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(confirmDelete||deleting)return;if(e.key==='ArrowRight'){e.preventDefault();next();}if(e.key==='ArrowLeft'){e.preventDefault();prev();}if(e.key===' '&&!(e.target instanceof HTMLButtonElement)){e.preventDefault();setPaused(p=>!p);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
  return <div className="sv" onClick={dismiss}><div ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-label={"Story by "+g.user.handle} className="sv-card" onClick={e=>e.stopPropagation()}>
    <div className="sv-bars" aria-hidden="true">{g.items.map((_,i)=><span key={g.user.id+'-'+i}><b style={{width:i<ii?'100%':i===ii?elapsed/duration*100+'%':'0%'}}/></span>)}</div>
    <div className="sv-h"><Avatar handle={g.user.handle} name={g.user.name} size={32} src={g.user.avatar}/><div className="sv-identity"><b>{g.user.handle}</b><small>{ago(it.created)} · {ii+1}/{g.items.length}</small></div>{g.user.id===me.id&&<button disabled={deleting} onClick={()=>{setConfirmDelete(true);setDeleteErr('');}} aria-label="Delete story"><Ic d={I.trash} size={18}/></button>}<button disabled={confirmDelete||deleting} onClick={()=>setPaused(p=>!p)} aria-label={paused?'Play story':'Pause story'}>{paused?'▶':'Ⅱ'}</button><button onClick={dismiss} disabled={deleting} aria-label="Close story"><Ic d={I.close}/></button></div>
    {!ready&&!failed&&<div className="sv-loading" role="status"><span className="spinner"/><span>Loading story…</span></div>}{failed?<div className="sv-loading"><p>This story could not load.</p><button className="ghost" onClick={next}>Next story</button></div>:<img key={it.id} src={img(it.image)} alt={"Story by "+g.user.handle} onLoad={()=>setReady(true)} onError={()=>setFailed(true)}/>}
    {confirmDelete&&<div className="sv-delete" role="alert"><p>Delete this story? This cannot be undone.</p>{deleteErr&&<p>{deleteErr}</p>}<div><button className="ghost" disabled={deleting} onClick={()=>{setConfirmDelete(false);setDeleteErr('');}}>Keep story</button><button className="danger" disabled={deleting} onClick={async()=>{setDeleting(true);try{await api.deleteStory(it.id);onDeleted();}catch(e:any){setDeleteErr(e.message);setDeleting(false);}}}>{deleting?'Deleting…':'Delete story'}</button></div></div>}
    <div className={'sv-gesture'+(confirmDelete?' blocked':'')+(failed?' failed':'')} onPointerDown={e=>{press.current={time:performance.now(),x:e.clientX,y:e.clientY,wasPaused:paused};e.currentTarget.setPointerCapture(e.pointerId);setPaused(true);}} onPointerCancel={()=>setPaused(press.current.wasPaused)} onPointerUp={e=>{const dx=e.clientX-press.current.x,dy=e.clientY-press.current.y;const held=performance.now()-press.current.time;setPaused(press.current.wasPaused);if(dy>90&&Math.abs(dx)<80){onClose();return;}if(Math.abs(dx)>60&&Math.abs(dy)<70){dx<0?next():prev();return;}if(held<250&&Math.abs(dx)<20&&Math.abs(dy)<20){const box=e.currentTarget.getBoundingClientRect();e.clientX-box.left<box.width*.35?prev():next();}}}/>
    <button disabled={confirmDelete||deleting} className="sv-access previous" onClick={prev} aria-label="Previous story"/><button disabled={confirmDelete||deleting} className="sv-access next" onClick={next} aria-label="Next story"/>
  </div></div>;
}
function More({ on, busy, onVisible }: { on: boolean; busy: boolean; onVisible: () => void }) {
  const ref = useRef<HTMLDivElement>(null); const cb = useRef(onVisible); cb.current = onVisible;
  useEffect(() => { const el = ref.current; if (!el || !on) return; const o = new IntersectionObserver(([e]) => { if(e.isIntersecting&&!busy)cb.current(); }, { rootMargin: '600px' }); o.observe(el); return () => o.disconnect(); }, [on, busy]);
  return on ? <div ref={ref} className="more">{busy && <span className="spinner" />}</div> : null;
}
function EditProfile({ me, onClose, onSaved }: { me: User; onClose: () => void; onSaved: (u: User) => void }) {
  const bioId=useId();const[copied,setCopied]=useState(false);const[copying,setCopying]=useState(false);const copyOperation=useRef(0);const copyLock=useRef(false);useEffect(()=>()=>{copyOperation.current++;},[]);
  const [name, setName] = useState(me.name); const [bio, setBio] = useState(me.bio || ''); const [busy, setBusy] = useState(false); const [err, setErr] = useState(''); const avatarInput=useRef<HTMLInputElement>(null);const [av,setAv]=useState<string|undefined>();const[removeAvatar,setRemoveAvatar]=useState(false);const [avatarBusy,setAvatarBusy]=useState(false);const avatarId=useRef(0);const saveLock=useRef(false);const recoveryLock=useRef(false); const [recovering,setRecovering]=useState(false);const [password,setPassword]=useState('');const [recovery,setRecovery]=useState('');const [recoverBusy,setRecoverBusy]=useState(false);useEffect(()=>()=>{avatarId.current++;},[]);const dismiss=()=>{if(!busy&&!recoverBusy)onClose();};const dialog=useDialog(dismiss);
  const pick=async(f?:File)=>{if(!f||busy||recoverBusy)return;const id=++avatarId.current;setAvatarBusy(true);setErr('');try{const data=await toDataUrl(f,400);if(id===avatarId.current){setAv(data);setRemoveAvatar(false);}}catch(x:any){if(id===avatarId.current)setErr(x.message||'Could not read that image');}finally{if(id===avatarId.current)setAvatarBusy(false);}};
  const save = async (e: React.FormEvent) => { e.preventDefault();if(saveLock.current||recoveryLock.current||avatarBusy)return;saveLock.current=true;setBusy(true); setErr(''); try { onSaved(await api.updateMe(name.trim()||me.handle,bio,av,removeAvatar)); } catch (x: any) { setErr(x.message); setBusy(false);saveLock.current=false; } };
  return <div className="scrim" onClick={dismiss}><div ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-label="Edit profile" className="modal edit-dialog" onClick={e => e.stopPropagation()}><form className="editm" onSubmit={save}>
    <h3>Edit profile</h3><button type="button" className="avpick" aria-label="Change profile photo" disabled={busy||recoverBusy} onClick={()=>avatarInput.current?.click()}><Avatar handle={me.handle} name={me.name} size={72} src={av||(removeAvatar?undefined:me.avatar)} /><span>Change photo</span></button><input ref={avatarInput} type="file" accept="image/*" hidden disabled={busy||recoverBusy} onChange={e=>{pick(e.target.files?.[0]);e.target.value='';}} />{(av||me.avatar)&&!removeAvatar&&<button type="button" className="link" disabled={busy||recoverBusy} onClick={()=>{avatarId.current++;setAvatarBusy(false);setAv(undefined);setRemoveAvatar(true);}}>Remove profile photo</button>}{avatarBusy&&<p className="avatar-status" role="status">Preparing profile photo…</p>}<label>Name<input disabled={busy||recoverBusy} value={name} maxLength={60} onChange={e => setName(e.target.value)} /></label>
    <div className="bio-field"><label htmlFor={bioId}>Bio</label><textarea id={bioId} disabled={busy||recoverBusy} value={bio} maxLength={200} rows={3} onChange={e => setBio(e.target.value)} /></div><small className="mut" aria-hidden="true">{bio.length}/200</small>
    <button type="button" className="ghost" disabled={busy||recoverBusy} onClick={()=>{setRecovering(r=>!r);setErr('');}}>Manage recovery code</button>
    {recovering&&<div className="recovery-panel">{recovery?<><p className="tag">Save this code somewhere private. Your previous code no longer works.</p><div className="rcode">{recovery}</div><button type="button" className="ghost" disabled={busy||recoverBusy||copying} onClick={async()=>{if(copyLock.current)return;copyLock.current=true;const id=++copyOperation.current;setCopying(true);try{await navigator.clipboard.writeText(recovery);if(id===copyOperation.current){setCopied(true);setErr('');}}catch{if(id===copyOperation.current){setCopied(false);setErr('Select and save the code manually.');}}finally{if(id===copyOperation.current){copyLock.current=false;setCopying(false);}}}}>{copying?'Copying…':copied?'Copied':'Copy code'}</button>{copied&&<span className="sr-only" role="status">Recovery code copied</span>}</>:<><p className="tag">Enter your password to replace your recovery code. The old code will stop working.</p><label>Password<input disabled={busy||recoverBusy} type="password" autoComplete="current-password" onKeyDown={e=>{if(e.key==='Enter')e.preventDefault();}} value={password} onChange={e=>setPassword(e.target.value)}/></label><button type="button" className="ghost" disabled={!password||busy||recoverBusy} onClick={async()=>{if(recoveryLock.current||saveLock.current)return;recoveryLock.current=true;setRecoverBusy(true);setErr('');try{const r=await api.newRecovery(password);setRecovery(r.recoveryCode);setCopied(false);setPassword('');}catch(x:any){setErr(x.message);}finally{recoveryLock.current=false;setRecoverBusy(false);}}}>{recoverBusy?'Creating…':'Create new code'}</button></>}</div>}

    {err && <p className="err" role="alert">{err}</p>}<div className="row"><button type="button" className="ghost" disabled={busy||recoverBusy} onClick={dismiss}>Cancel</button><button className="primary" disabled={busy||recoverBusy||avatarBusy}>{busy ? 'Saving…' : 'Save'}</button></div></form></div></div>;
}
export function App() {
  const [me, setMe] = useState<User | null>(null); const [ready,setReady]=useState(!hasToken());const [bootErr,setBootErr]=useState('');const [bootRetry,setBootRetry]=useState(0);
  const[,setClock]=useState(0);useEffect(()=>{if(!me)return;const tick=()=>{if(!document.hidden)setClock(n=>n+1);};const timer=setInterval(tick,60000);document.addEventListener('visibilitychange',tick);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',tick);};},[me?.id]);
  const [tab, setTab] = useState<Tab>('home'); const [feed, setFeed] = useState<Post[]>([]); const [explore, setExplore] = useState<Post[]>([]); const [saved, setSaved] = useState<Post[]>([]);
  const [prof, setProf] = useState<{ user: User; posts: Post[];next?:number|null } | null>(null); const [open, setOpen] = useState<Post | null>(null); const [dark, setDark] = useState(() => readStored('tl_dark') === '1');
  const [entry, setEntry] = useState<'landing' | 'login' | 'signup'>('landing'); const [feedNext, setFeedNext] = useState<number | null>(null); const [exploreNext, setExploreNext] = useState<number | null>(null); const [more, setMore] = useState(false);const [moreErr,setMoreErr]=useState('');const moreLock=useRef(false);const moreOperation=useRef(0); const [groups,setGroups]=useState<StoryGroup[]>([]);const[storiesErr,setStoriesErr]=useState(''); const [viewer, setViewer] = useState<number | null>(null); const [storyBusy,setStoryBusy]=useState(false);const [dmTo, setDmTo] = useState<string | null>(null); const [dmUnread, setDmUnread] = useState(0); const[profileMore,setProfileMore]=useState(false);const[profileMoreErr,setProfileMoreErr]=useState('');const profileMoreLock=useRef(false);const profileMoreOperation=useRef(0);const [editing, setEditing] = useState(false); const [notifs, setNotifs] = useState<Notif[]>([]); const [unread, setUnread] = useState(0);const [activityLoading,setActivityLoading]=useState(true);const [activityErr,setActivityErr]=useState('');const [activityRetry,setActivityRetry]=useState(0); const [q, setQ] = useState('');const[searchRetry,setSearchRetry]=useState(0); const [results, setResults] = useState<User[]>([]); const [postHits, setPostHits] = useState<Post[]>([]); const [toast, setToast] = useState(''); const [loading, setLoading] = useState(false); const [refreshErr,setRefreshErr]=useState('');const refreshId=useRef(0);const storiesId=useRef(0);const profileId=useRef(0);const [searching,setSearching]=useState(false);const [searchErr,setSearchErr]=useState('');const [following,setFollowing]=useState<number[]>([]);const followLocks=useRef(new Set<number>());
  const [messageDrafts,setMessageDrafts]=useState<MessageDrafts>({});const [messagePending,setMessagePending]=useState<Set<string>>(new Set());const draftSession=useRef(0);const[messageErrors,setMessageErrors]=useState<Record<string,string>>({});
  const photoDraft=useRef<PhotoDraft>({fileName:'',caption:''});const[photoBusy,setPhotoBusy]=useState(false);const[photoRevision,setPhotoRevision]=useState(0);const[photoErr,setPhotoErr]=useState('');
  const bottomNav=useRef<HTMLElement>(null);const topHeader=useRef<HTMLElement>(null);
  useEffect(()=>{const nav=bottomNav.current;if(!nav)return;const root=document.documentElement;const update=()=>{const height=nav.getBoundingClientRect().height;root.style.setProperty('--tl-nav-height',height>0?height+'px':'76px');};const observer=new ResizeObserver(update);observer.observe(nav);const header=topHeader.current;const updateHeader=()=>{const h=header?.getBoundingClientRect().height||0;root.style.setProperty('--tl-header-height',h>0?h+'px':'56px');};const headerObserver=new ResizeObserver(updateHeader);if(header)headerObserver.observe(header);updateHeader();update();return()=>{observer.disconnect();headerObserver.disconnect();root.style.removeProperty('--tl-nav-height');root.style.removeProperty('--tl-header-height');};},[me?.id]);
  const storyInput=useRef<HTMLInputElement>(null);const storyLock=useRef(false);const keyboardMode=useRef(false);
  useEffect(()=>{const key=()=>{keyboardMode.current=true;};const pointer=()=>{keyboardMode.current=false;};document.addEventListener('keydown',key);document.addEventListener('pointerdown',pointer);return()=>{document.removeEventListener('keydown',key);document.removeEventListener('pointerdown',pointer);};},[]);
  useEffect(()=>{if(!me||!keyboardMode.current)return;document.getElementById('main-content')?.focus({preventScroll:true});},[me?.id,tab,prof?.user.id]);
  const toastTimer=useRef<ReturnType<typeof setTimeout>>();const say=(m:string)=>{clearTimeout(toastTimer.current);setToast(m);toastTimer.current=setTimeout(()=>setToast(''),2600);};useEffect(()=>()=>clearTimeout(toastTimer.current),[]);
  useEffect(() => { let active=true;setOnAuthLost(()=>{photoDraft.current={fileName:'',caption:''};moreOperation.current++;moreLock.current=false;setMore(false);setMoreErr('');profileMoreOperation.current++;profileMoreLock.current=false;setProfileMore(false);setProfileMoreErr('');setStoryBusy(false);storyLock.current=false;setPhotoBusy(false);setPhotoErr('');draftSession.current++;followLocks.current.clear();setFollowing([]);setMessageDrafts({});setMessagePending(new Set());setMessageErrors({});refreshId.current++;storiesId.current++;profileId.current++;setMe(null);setFeed([]);setExplore([]);setSaved([]);setProf(null);setGroups([]);setNotifs([]);setOpen(null);setEditing(false);setViewer(null);setDmTo(null);setQ('');setResults([]);setPostHits([]);setUnread(0);setDmUnread(0);setTab('home');setEntry('login');}); if(hasToken()){setReady(false);setBootErr('');api.me().then(u=>{if(active)setMe(u);}).catch(e=>{if(active&&hasToken())setBootErr(e.message);}).finally(()=>{if(active)setReady(true);});}return()=>{active=false;};},[bootRetry]);
  useEffect(()=>{writeStored('tl_dark',dark?'1':'0');document.querySelector('meta[name=theme-color]')?.setAttribute('content',dark?'#1b1b18':'#f6f3ed');document.documentElement.style.colorScheme=dark?'dark':'light';},[dark]);
  const loadProfile=useCallback(async(h:string)=>{profileMoreOperation.current++;profileMoreLock.current=false;setProfileMore(false);const id=++profileId.current;try{const p=await api.profile(h);if(id===profileId.current){setProf(p);setProfileMoreErr('');setTab('profile');window.scrollTo({top:0,behavior:'instant' as ScrollBehavior});}}catch(e:any){if(id===profileId.current)say(e.message);}},[]);
  const refresh = useCallback(async () => {
    if(!me)return;moreOperation.current++;moreLock.current=false;setMore(false);const id=++refreshId.current;setLoading(true);setRefreshErr('');setMoreErr('');
    try { const [f, e, s] = await Promise.all([api.feed(), api.explore(), api.saved()]);if(id!==refreshId.current)return; setFeed(f.posts); setFeedNext(f.next); setExplore(e.posts); setExploreNext(e.next); setSaved(s.posts); if(tab==='profile'&&prof){const pid=profileId.current;const p=await api.profile(prof.user.handle);if(id===refreshId.current&&pid===profileId.current)setProf(p);} }catch(e:any){if(id===refreshId.current)setRefreshErr(e.message);}finally{if(id===refreshId.current)setLoading(false);}
  }, [me, tab, prof?.user.handle]);
  const loadStories=useCallback(()=>{const id=++storiesId.current;setStoriesErr('');api.stories().then(r=>{if(id===storiesId.current){setGroups(r.groups);setStoriesErr('');}}).catch(e=>{if(id===storiesId.current)setStoriesErr(e.message);});},[]);
  useEffect(() => { if (me) { refresh(); if (tab === 'home') loadStories(); } }, [me, tab]);
  useEffect(()=>{if(!me)return;let active=true;let pulling=false;setActivityLoading(true);setActivityErr('');const pull=()=>{if(document.hidden||pulling)return;pulling=true;Promise.all([api.notifications().then(r=>{if(active){setNotifs(r.items);setUnread(r.unread);setActivityErr('');}}).catch(e=>{if(active)setActivityErr(e.message);}).finally(()=>{if(active)setActivityLoading(false);}),api.conversations().then(r=>{if(active)setDmUnread(r.unread);}).catch(()=>{})]).finally(()=>{pulling=false;});};pull();const t=setInterval(pull,30000);document.addEventListener('visibilitychange',pull);return()=>{active=false;clearInterval(t);document.removeEventListener('visibilitychange',pull);};},[me,tab,activityRetry]);
  useEffect(() => {const through=Math.max(0,...notifs.filter(n=>!n.seen).map(n=>n.id));if(tab!=='activity'||!unread||!through)return;let active=true;const t=setTimeout(()=>api.readNotifications(through).then(async()=>{if(!active)return;try{const r=await api.notifications();if(active){setNotifs(r.items);setUnread(r.unread);}}catch{if(active){const count=notifs.filter(n=>!n.seen&&n.id<=through).length;setUnread(n=>Math.max(0,n-count));setNotifs(n=>n.map(x=>x.id<=through?{...x,seen:true}:x));}}}).catch(()=>{}),1200);return()=>{active=false;clearTimeout(t);};},[tab,unread,notifs.map(n=>n.id+':'+n.seen).join(',')]);
  useEffect(() => { let active=true;setResults([]);setPostHits([]);setSearchErr('');setSearching(!!q.trim());if(!q.trim())return;const t=setTimeout(()=>api.search(q).then(r=>{if(active){setResults(r.users);setPostHits(r.posts||[]);}}).catch(e=>{if(active)setSearchErr(e.message);}).finally(()=>{if(active)setSearching(false);}),250);return()=>{active=false;clearTimeout(t);}; }, [q,searchRetry]);
  const loadMore = useCallback(async (kind: 'feed' | 'explore') => {
    if (loading||moreLock.current) return; const next = kind === 'feed' ? feedNext : exploreNext; if (!next) return; const requestId=refreshId.current;const generation=draftSession.current;const operation=++moreOperation.current;moreLock.current=true;setMore(true);setMoreErr('');
    try { const r = await (kind === 'feed' ? api.feed(next) : api.explore(next)); if(requestId!==refreshId.current)return;const add = (l: Post[]) => [...l, ...r.posts.filter(p => !l.some(x => x.id === p.id))];
      if (kind === 'feed') { setFeed(add); setFeedNext(r.next); } else { setExplore(add); setExploreNext(r.next); } } catch(e:any){if(requestId===refreshId.current)setMoreErr(e.message);} finally {if(generation===draftSession.current&&operation===moreOperation.current){moreLock.current=false;setMore(false);}}
  }, [more, loading, feedNext, exploreNext]);
  const loadMoreProfile=async()=>{if(profileMoreLock.current||!prof?.next)return;const id=profileId.current;const generation=draftSession.current;const operation=++profileMoreOperation.current;const handle=prof.user.handle;profileMoreLock.current=true;setProfileMore(true);setProfileMoreErr('');try{const r=await api.profile(handle,prof.next);if(id===profileId.current)setProf(p=>p&&p.user.handle===handle?{...p,posts:[...p.posts,...r.posts.filter(x=>!p.posts.some(y=>y.id===x.id))],next:r.next}:p);}catch(e:any){if(id===profileId.current)setProfileMoreErr(e.message);}finally{if(generation===draftSession.current&&operation===profileMoreOperation.current){profileMoreLock.current=false;setProfileMore(false);}}};
  const upd = (p: Post) => { const m = (l: Post[]) => l.map(x => x.id === p.id ? p : x); setFeed(m); setExplore(m); setSaved(s => p.saved ? (s.some(x => x.id === p.id) ? m(s) : [p, ...s]) : s.filter(x => x.id !== p.id)); setProf(pr => pr && { ...pr, posts: m(pr.posts) }); setOpen(o => o && o.id === p.id ? p : o); };
  const del = async (id: number) => { const generation=draftSession.current;try { await api.deletePost(id);if(generation!==draftSession.current)return false; const f = (l: Post[]) => l.filter(x => x.id !== id); setFeed(f); setExplore(f); setSaved(f); setProf(pr=>pr&&{...pr,posts:f(pr.posts),user:pr.posts.some(p=>p.id===id)?{...pr.user,posts:Math.max(0,pr.user.posts-1)}:pr.user}); say('Post deleted');return true;}catch(e:any){if(generation===draftSession.current)say(e.message);return false;}};
  const follow=async(u:User)=>{if(followLocks.current.has(u.id))return;const generation=draftSession.current;followLocks.current.add(u.id);setFollowing(v=>[...v,u.id]);try { const nu = await api.follow(u.handle, !u.followedByMe);if(generation!==draftSession.current)return; setResults(r => r.map(x => x.id === nu.id ? nu : x)); setProf(p => p && p.user.id === nu.id ? { ...p, user: nu } : p); const id=refreshId.current;api.feed().then(r=>{if(id===refreshId.current){setFeed(r.posts);setFeedNext(r.next);}}).catch(()=>{}); }catch(e:any){if(generation===draftSession.current)say(e.message);}finally{if(generation===draftSession.current){followLocks.current.delete(u.id);setFollowing(v=>v.filter(x=>x!==u.id));}}};
  const logout=()=>{photoDraft.current={fileName:'',caption:''};moreOperation.current++;moreLock.current=false;setMore(false);setMoreErr('');profileMoreOperation.current++;profileMoreLock.current=false;setProfileMore(false);setProfileMoreErr('');setStoryBusy(false);storyLock.current=false;setPhotoBusy(false);setPhotoErr('');draftSession.current++;followLocks.current.clear();setFollowing([]);setMessageDrafts({});setMessagePending(new Set());setMessageErrors({});refreshId.current++;storiesId.current++;profileId.current++;setRefreshErr('');setToken('');setMe(null);setGroups([]);setFeed([]);setExplore([]);setSaved([]);setProf(null);setOpen(null);setViewer(null);setEditing(false);setDmTo(null);setQ('');setResults([]);setPostHits([]);setNotifs([]);setUnread(0);setDmUnread(0);setTab('home');setEntry('login');};
  const renderedSession=draftSession.current;
  const cls = 'ig' + (dark ? ' dark' : '');
  if(bootErr)return <div className={cls}><div className="authwrap" role="main"><div className="authcard"><h1 className="logo">Threadline</h1><p className="err" role="alert">{bootErr}</p><button className="primary" onClick={()=>setBootRetry(n=>n+1)}>Try again</button><button className="ghost" onClick={()=>{setBootErr('');logout();}}>Log out</button></div></div></div>;
  if (!ready) return <div className={cls}><div className="loading" role="main" aria-label="Loading Threadline"><h1 className="sr-only">Threadline</h1><span className="spinner" role="status" aria-label="Loading" /></div></div>;
  if (!me) return <div className={cls}>{entry === 'landing' ? <Landing onStart={setEntry} /> : <Auth key={entry} initial={entry} onBack={() => setEntry('landing')} onAuth={u => { setMe(u); setTab('home'); }} />}</div>;
  const nav: [Tab, string][] = [['home', I.home], ['explore', I.search], ['create', I.plus], ['messages', I.send], ['activity', I.bell], ['saved', I.bookmark], ['profile', I.user]];
  const badge = (t: Tab) => { const n = t === 'activity' ? unread : t === 'messages' ? dmUnread : 0; return n > 0 ? <i className="badge">{n > 9 ? '9+' : n}</i> : null; };
  const go = (t: Tab) => { profileId.current++;setOpen(null); setEditing(false); if (t === 'profile') loadProfile(me.handle); else setTab(t); window.scrollTo({top:0,behavior:'instant' as ScrollBehavior}); };
  const card = (p: Post, index: number) => <PostCard priority={index===0} key={p.id} post={p} me={me} onChange={p=>{if(renderedSession===draftSession.current)upd(p);}} onOpen={() => setOpen(p)} onUser={loadProfile} onDelete={del} />;
  return <div className={cls}>
    <a className="skip-link" href="#main-content">Skip to content</a><aside className="side" aria-label="App navigation"><h1 className="logo"><BrandMark />Threadline</h1>
      {nav.map(([t, d]) => <button key={t} aria-label={t[0].toUpperCase()+t.slice(1)} aria-current={tab===t?'page':undefined} className={tab === t ? 'on' : ''} onClick={() => go(t)}><Ic d={d} fill={tab === t && t !== 'create'} />{badge(t)}<span>{t[0].toUpperCase() + t.slice(1)}</span></button>)}
      <button className="push" aria-label={dark?'Light mode':'Dark mode'} onClick={()=>setDark(!dark)}><Ic d={I.moon} /><span>{dark ? 'Light' : 'Dark'} mode</span></button>
      <button aria-label="Log out" onClick={logout}><Ic d={I.logout} /><span>Log out</span></button></aside>
    <header ref={topHeader} className="top"><h1 className="logo"><BrandMark />Threadline</h1><span><button onClick={() => setDark(!dark)} aria-label="Toggle dark mode"><Ic d={I.moon} /></button> <button onClick={logout} aria-label="Log out"><Ic d={I.logout} /></button></span></header>
    <main key={tab} className="page" id="main-content" tabIndex={-1}>
      {refreshErr&&['home','explore','saved'].includes(tab)&&<div className="load-error" role="alert"><p>{refreshErr}</p><button className="ghost" onClick={refresh}>Try again</button></div>}
      {tab==='home'&&<div className="home"><section className="col"><div className="feed-heading"><span>Your people</span><button className="link" disabled={loading} onClick={()=>{refresh();loadStories();}}>{loading?'Refreshing…':'Refresh'}</button></div>{storiesErr&&<div className="stories-error" role="alert"><span>Stories could not load.</span><button className="link" onClick={loadStories}>Retry stories</button></div>}
        <div className="stories"><div className="story add"><button className="story-picker" type="button" aria-label="Add your story" disabled={storyBusy} onClick={()=>storyInput.current?.click()}><span className="av-wrap" style={{ width: 62, height: 62 }}><Avatar handle={me.handle} name={me.name} size={58} src={me.avatar} /><i className="plus">+</i></span><small>{storyBusy?'Sharing…':'Your story'}</small></button>
          <input ref={storyInput} type="file" accept="image/*" disabled={storyBusy} hidden onChange={async e => { const f = e.target.files?.[0]; e.target.value = ''; if(!f||storyLock.current)return;const generation=draftSession.current;storyLock.current=true;setStoryBusy(true);try { const image=await toDataUrl(f);if(generation!==draftSession.current)return;await api.addStory(image);if(generation!==draftSession.current)return;say('Story shared');loadStories(); } catch(x:any){if(generation===draftSession.current)say(x.message);}finally{if(generation===draftSession.current){storyLock.current=false;setStoryBusy(false);}} }} /></div>
          {groups.map((g, i) => <button aria-label={"View story by "+g.user.handle} key={g.user.id} className="story" onClick={() => setViewer(i)}><Avatar handle={g.user.handle} name={g.user.name} size={58} story src={g.user.avatar} /><small>{g.user.id === me.id ? 'You' : g.user.handle}</small></button>)}</div>
        {loading&&<span className="sr-only" role="status" aria-label="Loading your feed">Loading your feed…</span>}{feed.length === 0 && loading && [0, 1].map(i => <div key={i} className="post sk" aria-hidden="true"><div className="sk-h"><i /><b /></div><div className="sk-m" /><div className="sk-l" /></div>)}
        {feed.length===0&&!loading&&!refreshErr&& <div className="quiet-start feed-start"><h2>Your feed is empty.</h2><p>Follow people on Explore, or share your first photo.</p><button className="ghost" onClick={() => go('explore')}>Find people</button></div>}
        {feed.map(card)}{moreErr&&<div className="load-error" role="alert"><p>{moreErr}</p><button className="ghost" disabled={more} onClick={()=>loadMore('feed')}>Try again</button></div>}<More on={!loading&&!!feedNext&&!moreErr} busy={more} onVisible={()=>loadMore('feed')}/></section>
        <aside className="rail" aria-label="Your profile"><div className="meu"><Avatar handle={me.handle} name={me.name} size={46} src={me.avatar} /><div><b>{me.handle}</b><small>{me.name}</small></div></div></aside></div>}
      {tab === 'explore' && <div className="wide"><div className="section-heading"><h2>Explore</h2><p>Search for people or browse photographs.</p></div><div className="search"><Ic d={I.search} size={18} /><input value={q} onChange={e => setQ(e.target.value)} aria-label="Search people and posts" placeholder="Search people and posts" />{q&&<button className="search-clear" aria-label="Clear search" onClick={()=>setQ('')}><Ic d={I.close} size={18}/></button>}</div>
        {q.trim() ? <>{results.filter(u => u.id !== me.id).map(u => <div key={u.id} className="sug big"><button aria-label={"Open profile of "+u.handle} onClick={() => loadProfile(u.handle)}><Avatar handle={u.handle} name={u.name} size={44} src={u.avatar} /></button><div className="search-person"><button className="person-name" aria-label={"View profile of "+u.handle} onClick={()=>loadProfile(u.handle)}>{u.handle}</button><small>{u.name}</small><small className="search-followers">{u.followers} followers</small></div><button className={u.followedByMe ? 'ghost' : 'primary sm'} disabled={following.includes(u.id)} onClick={()=>follow(u)}>{u.followedByMe ? 'Following' : 'Follow'}</button></div>)}
          {postHits.length > 0 && <><h3 className="hits">Posts</h3><Grid posts={postHits} onOpen={setOpen} /></>}
          {searching&&<p className="empty" role="status">Searching…</p>}{searchErr&&<div className="search-error err" role="alert"><p>{searchErr}</p><button className="ghost" onClick={()=>setSearchRetry(n=>n+1)}>Try again</button></div>}{!searching&&!searchErr&&!results.some(u=>u.id!==me.id)&&!postHits.length&&<p className="empty search-empty">Nothing found for "{q.length>80?q.slice(0,80)+'…':q}".</p>}</> : <>{loading&&!explore.length?<p className="empty" role="status">Loading photos…</p>:(!refreshErr||explore.length>0)&&(explore.length?<Grid posts={explore} onOpen={setOpen}/>:<div className="quiet-start"><h3>No photographs yet.</h3><p>Search for someone by name, or share the first photograph.</p><button className="ghost" onClick={()=>go('create')}>Share a photograph</button></div>)}{moreErr&&<div className="load-error" role="alert"><p>{moreErr}</p><button className="ghost" disabled={more} onClick={()=>loadMore('explore')}>Try again</button></div>}<More on={!loading&&!!exploreNext&&!moreErr} busy={more} onVisible={()=>loadMore('explore')}/></>}</div>}
      {tab === 'create' && <Create draft={photoDraft} session={draftSession} err={photoErr} setErr={setPhotoErr} busy={photoBusy} setBusy={setPhotoBusy} revision={photoRevision} changed={()=>setPhotoRevision(n=>n+1)} done={() => { say('Posted'); loadProfile(me.handle); }} />}
      {tab === 'messages' && <Messages sendErrors={messageErrors} setSendErrors={setMessageErrors} drafts={messageDrafts} setDrafts={setMessageDrafts} pending={messagePending} setPending={setMessagePending} session={draftSession} onExplore={()=>go('explore')} me={me} to={dmTo} setTo={setDmTo} onUser={loadProfile} onRead={() => api.conversations().then(r => {if(renderedSession===draftSession.current)setDmUnread(r.unread);}).catch(() => {})} />}
      {tab === 'activity' && <div className="wide"><div className="section-heading"><h2>Activity</h2><p>Likes, comments and new followers.</p></div>{activityLoading&&!notifs.length&&<p className="empty" role="status">Loading activity…</p>}{activityErr&&<div className="load-error" role="alert"><p>{activityErr}</p><button className="ghost" onClick={()=>setActivityRetry(n=>n+1)}>Try again</button></div>}{!activityLoading&&!activityErr&&notifs.length===0&&<div className="quiet-start"><h3>Nothing new yet.</h3><p>When someone follows you or responds to a photograph, you'll see it here.</p></div>}
        {notifs.map((n, i) => <div key={n.id} className={'notif' + (n.seen ? '' : ' new')} style={{ animationDelay: Math.min(i, 10) * 40 + 'ms' }}>
          <button aria-label={"Open profile of "+n.user.handle} onClick={() => loadProfile(n.user.handle)}><Avatar handle={n.user.handle} name={n.user.name} size={44} src={n.user.avatar} /></button>
          <div className="notification-copy"><div className="notification-meta"><button className="person-name" aria-label={"View profile of "+n.user.handle} onClick={()=>loadProfile(n.user.handle)}>{n.user.handle}</button><small>{ago(n.created)}</small></div><p>{n.type === 'like' ? 'Liked your photograph.' : n.type === 'comment' ? 'Left a comment.' : 'Started following you.'}</p>{n.type==='comment'&&n.text&&<p className="notification-comment">{n.text}</p>}</div>
          {n.image&&n.postId&&<button className="notif-photo" aria-label="Open notification photo" onClick={async()=>{try{const id=refreshId.current;const post=await api.post(n.postId!);if(id===refreshId.current)setOpen(post);}catch(e:any){say(e.message);}}}><NotificationImage src={n.image}/></button>}</div>)}</div>}
      {tab === 'saved' && <div className="wide"><div className="section-heading"><h2>Saved</h2><p>Photographs you want to come back to.</p></div>{loading&&!saved.length?<p className="empty" role="status">Loading saved moments…</p>:(!refreshErr||saved.length>0)&&(saved.length?<Grid posts={saved} onOpen={setOpen}/>:<div className="quiet-start"><h3>No saved photographs yet.</h3><p>Tap the bookmark on a photograph to keep it here.</p><button className="ghost" onClick={()=>go('explore')}>Explore photographs</button></div>)}</div>}
      {tab === 'profile' && prof && <div className="wide"><div className="prof"><Avatar handle={prof.user.handle} name={prof.user.name} size={96} src={prof.user.avatar} /><div className="profile-details"><h2><span className="profile-handle">{prof.user.handle}</span></h2><div className="profile-controls">
        {prof.user.id === me.id && <button className="ghost" onClick={() => setEditing(true)}>Edit profile</button>}
        {prof.user.id !== me.id && <button className="ghost" onClick={() => { setDmTo(prof.user.handle); setTab('messages'); }}>Message</button>}
        {prof.user.id !== me.id && <button className={prof.user.followedByMe ? 'ghost' : 'primary sm'} disabled={following.includes(prof.user.id)} onClick={()=>follow(prof.user)}>{prof.user.followedByMe ? 'Following' : 'Follow'}</button>}</div>
        <div className="stats"><span><b>{prof.user.posts}</b> {prof.user.posts===1?"post":"posts"}</span><span><b>{prof.user.followers}</b> {prof.user.followers===1?"follower":"followers"}</span><span><b>{prof.user.following}</b> following</span></div><p className="profile-name">{prof.user.name}</p>{prof.user.bio&&<p className="profile-bio">{prof.user.bio}</p>}</div></div><div className="profile-photos-heading"><span>Photographs</span><small>{prof.user.posts} {prof.user.posts===1?"photo":"photos"}</small></div>{prof.posts.length===0&&prof.user.id===me.id?<div className="profile-start"><p>Your first photograph.</p><span>A place, a person, a detail you noticed. Start with something you want to keep.</span><button className="primary" onClick={()=>go('create')}>Share a photo</button></div>:<Grid posts={prof.posts} onOpen={setOpen} />}{profileMoreErr&&<div className="load-error" role="alert"><p>{profileMoreErr}</p><button className="ghost" disabled={profileMore} onClick={loadMoreProfile}>Try again</button></div>}<More on={!!prof.next&&!profileMoreErr} busy={profileMore} onVisible={loadMoreProfile}/></div>}
    </main>
    <nav ref={bottomNav} className="bottom" aria-label="Main navigation">{nav.map(([t, d]) => <button key={t} className={tab === t ? 'on' : ''} onClick={() => go(t)} aria-label={t} aria-current={tab === t ? "page" : undefined}><Ic d={d} fill={tab === t && t !== 'create'} /><span className="nav-label" aria-hidden="true">{t==='messages'?'Messages':t[0].toUpperCase()+t.slice(1)}</span>{badge(t)}</button>)}</nav>
    {open && <Modal post={open} me={me} onChange={p=>{if(renderedSession===draftSession.current)upd(p);}} onClose={() => {if(renderedSession===draftSession.current)setOpen(current=>current?.id===open.id?null:current);}} onUser={loadProfile} onDelete={del} />}
    {viewer !== null && groups[viewer] && <StoryViewer groups={groups} start={viewer} me={me} onClose={()=>setViewer(null)} onDeleted={()=>{if(renderedSession!==draftSession.current)return;setViewer(null);loadStories();say('Story deleted');}}/>}
    {editing && <EditProfile me={me} onClose={() => setEditing(false)} onSaved={u => { if(renderedSession!==draftSession.current)return;setMe(u); setEditing(false); loadProfile(u.handle); say('Profile updated'); }} />}
    {!readStored('tl_token')&&hasToken()&&<div className="session-note" role="status">Session is temporary. Your browser is not allowing saved sign-ins.</div>}{toast && <div className="toast" role="status">{toast}</div>}
  </div>;
}
