import React,{useEffect,useRef,useState} from 'react';import {api,DeveloperKey} from './api';
export function Developer(){
 const [keys,setKeys]=useState<DeveloperKey[]>([]),[name,setName]=useState(''),[revealed,setRevealed]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0),[status,setStatus]=useState('');const alive=useRef(true),lock=useRef(false),copyTarget=useRef<HTMLTextAreaElement>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{let current=true;setLoading(true);setError('');api.developerKeys().then(r=>{if(current)setKeys(r.keys);}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[retry]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');setStatus('');setRevealed('');try{const r=await api.createKey(name);if(!alive.current)return;setRevealed(r.key);setKeys(k=>[{id:r.id,name:r.name,prefix:r.prefix,created:r.created,revoked:false},...k]);setName('');setStatus('API key created. Save it now; it is shown only once.');}catch(e:any){if(alive.current)setError(e.message);}finally{lock.current=false;if(alive.current)setBusy(false);}};
 const revoke=async(key:DeveloperKey)=>{if(lock.current)return;if(!window.confirm('Revoke '+key.name+'? Apps using this key will lose access immediately.'))return;lock.current=true;setBusy(true);setError('');try{await api.revokeKey(key.id);if(alive.current){setKeys(k=>k.map(x=>x.id===key.id?{...x,revoked:true}:x));if(revealed.startsWith(key.prefix))setRevealed('');setStatus('Key revoked.');}}catch(e:any){if(alive.current)setError(e.message);}finally{lock.current=false;if(alive.current)setBusy(false);}};
 return <section className="wide developer" aria-labelledby="developer-title"><div className="section-heading"><h2 id="developer-title">Developer API</h2><p>Read your profile and photographs from your own app.</p></div><p className="developer-intro">Keys have read-only access to your own data, not messages, recovery codes or other accounts. Each key allows 60 requests per minute across servers. Treat keys like passwords. Account recovery revokes them.</p><a className="developer-docs" href="/developers.html" target="_blank" rel="noreferrer">Read API documentation</a>
 <form onSubmit={create} className="developer-form"><label htmlFor="developer-key-name">Key name</label><input id="developer-key-name" value={name} maxLength={60} required placeholder="My app" disabled={busy} onChange={e=>setName(e.target.value)}/><button className="primary" disabled={busy||loading||keys.filter(k=>!k.revoked).length>=5}>{busy?'Working...':'Create read-only key'}</button><small>Up to five active keys. A key appears only once after creation.</small></form>
 {revealed&&<div className="developer-secret"><label htmlFor="developer-secret">New API key. Copy and store it securely.</label><textarea id="developer-secret" ref={copyTarget} readOnly value={revealed} spellCheck={false}/><button className="ghost" onClick={async()=>{try{await navigator.clipboard.writeText(revealed);if(alive.current)setStatus('Key copied.');}catch{copyTarget.current?.focus();copyTarget.current?.select();if(alive.current)setStatus('Copy is unavailable. Select the key and copy it manually.');}}}>Copy key</button><button className="ghost" onClick={()=>setRevealed('')}>Hide key</button><p>This key disappears when you leave this screen or reload. It is never stored in your browser.</p></div>}
 {status&&<p role="status">{status}</p>}{error&&<div className="load-error" role="alert"><p>{error}</p><button className="ghost" disabled={busy} onClick={()=>setRetry(n=>n+1)}>Reload keys</button></div>}{loading&&<p role="status">Loading keys...</p>}
 <h3>Your keys</h3>{!loading&&!keys.length&&<p>No keys yet.</p>}<ul className="developer-keys">{keys.map(k=><li key={k.id}><div><b>{k.name}</b><small>{k.prefix}... · {k.revoked?'Revoked':'Read only'} · {new Date(k.created).toLocaleDateString()}</small></div>{!k.revoked&&<button className="ghost" disabled={busy} aria-label={'Revoke '+k.name} onClick={()=>revoke(k)}>Revoke</button>}</li>)}</ul></section>;
}
